### ISSUE TITLE
Discontiguous ranges?

### ISSUE THREAD

**Issue by ghost** [BurntSushi/utf8-ranges#9]
Great package, but how does one convert discontiguous ranges to a series of byte ranges? For example, `[а-мо-я]`? It's not unusual for regular expressions to have ranges with holes in them.

If you convert `[а-м]` and `[о-я]` separately, the corresponding byte ranges would intersect: `[{208 208} {176 188}]` and `[{208 208} {190 191}]`.

**Comment by BurntSushi** [comment]
Sorry but I don't see the problem. Your ranges don't look like they intersect to me. They just have a common prefix. Could you please elaborate on what it is you expect to happen?

**Comment by ghost** [comment]
Yes, I'm talking about the common prefix. This prefix becomes a single state transition in an automaton, and then the resulting state has to fork. I guess it's just me being dense. I just have to sit and implement it.

**Comment by BurntSushi** [comment]
I mean, that's true even for continuous ranges too, which emit many byte sequences with common prefixes. I mean, take a look at `\p{WhiteSpace}`:

```
$ regex-debug utf8-ranges '\p{WhiteSpace}'
[09-0D]
----------------------------
[20-20]
----------------------------
[C2-C2][85-85]
----------------------------
[C2-C2][A0-A0]
----------------------------
[E1-E1][9A-9A][80-80]
----------------------------
[E2-E2][80-80][80-8A]
----------------------------
[E2-E2][80-80][A8-A9]
----------------------------
[E2-E2][80-80][AF-AF]
----------------------------
[E2-E2][81-81][9F-9F]
----------------------------
[E3-E3][80-80][80-80]
```

**Comment by ghost** [comment]
But `\p{WhiteSpace}` isn't a single contiguous range, so that's not surprising at all.

**Comment by BurntSushi** [comment]
Ah right sure, but in order for something to be surprising, you need to tell me what you _expect_ to happen. :-)

**Comment by ghost** [comment]
I guess I'm just looking for an algorithm which translates these byte ranges (that can share a common prefix) into a deterministic FA. (If they don't share a prefix, that's easy enough - you can translate them separately and simply join the resulting automata, given that their states are uniquely numbered.)

**Comment by BurntSushi** [comment]
OK, in that case, I'd say that's outside the scope of this crate, since there are many such algorithms, and the one you select depends a lot on the space-vs-time trade off you're willing to make.
